export async function GET(request: Request) {
  const { origin } = new URL(request.url)

  const lines = [
    "# robots.txt for Weblyst — Digital Marketing & Web Development Solutions",
    "# Allow AI crawlers and search engines for better discoverability",
    "",
    "User-agent: GPTBot",
    "Allow: /",
    "Disallow: /api/",
    "Disallow: /admin/",
    "Disallow: /checkout/",
    "",
    "User-agent: ChatGPT-User",
    "Allow: /",
    "Disallow: /api/",
    "Disallow: /admin/",
    "Disallow: /checkout/",
    "",
    "User-agent: ClaudeBot",
    "Allow: /",
    "Disallow: /api/",
    "Disallow: /admin/",
    "Disallow: /checkout/",
    "",
    "User-agent: CCBot",
    "Allow: /",
    "Disallow: /api/",
    "Disallow: /admin/",
    "Disallow: /checkout/",
    "",
    "User-agent: PerplexityBot",
    "Allow: /",
    "Disallow: /api/",
    "Disallow: /admin/",
    "Disallow: /checkout/",
    "",
    "User-agent: Googlebot",
    "Allow: /",
    "Disallow: /api/",
    "Disallow: /admin/",
    "Disallow: /checkout/",
    "",
    "User-agent: Bingbot",
    "Allow: /",
    "Disallow: /api/",
    "Disallow: /admin/",
    "Disallow: /checkout/",
    "",
    "User-agent: *",
    "Allow: /",
    "Disallow: /api/",
    "Disallow: /admin/",
    "Disallow: /checkout/",
    "",
    `Sitemap: ${origin}/sitemap.xml`,
  ].join("\n")

  return new Response(lines, {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "public, max-age=3600",
    },
  })
}
